### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by creeperplayer20** [Tobikisss/Giftcode#1]
#0 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[13] GiftCode\Main)
#1 (): BaseClassLoader->{closure}(string[13] GiftCode\Main)
#2 (): spl_autoload_call(string[13] GiftCode\Main)
#3 src/pocketmine/plugin/PluginManager(165): class_exists(string[13] GiftCode\Main, boolean 1)
#4 src/pocketmine/plugin/PluginManager(335): pocketmine\plugin\PluginManager->loadPlugin(string[43] /home/minecraft/plugins/Giftcode_dev-6.phar, array[2])
#5 src/pocketmine/Server(1527): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/minecraft/plugins/)
#6 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#7 src/pocketmine/PocketMine(296): pocketmine\server()
#8 (11): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

**Comment by Tobikisss** [comment]
Hey. Was ist on initial start of the server?

**Comment by Tobikisss** [comment]
Sand could you send the whole error message?

**Comment by creeperplayer20** [comment]
I added this plugin to the plugins folder, then i restarted the server and it crashed...

**Comment by Tobikisss** [comment]
Ok. I'll try to fix that. Could you send me the complete error code/response?

**Comment by Tobikisss** [comment]
clossed due to no errorreply/response
